[2018-11-15 14:35:04] ERROR [django.request.handle_uncaught_exception:118] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\cursors.py", line 247, in execute
    res = self._query(query)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\cursors.py", line 374, in _do_query
    db.query(q)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'linuxjobber.courses_course' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Mololuwa\Desktop\SamuelLinuxjobber\Django\Linuxjobber\home\views.py", line 35, in index
    return render (request, 'home/index.html', {'courses' : get_courses(), 'tools' : get_tools()})
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\template\defaulttags.py", line 313, in render
    if match:
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\query.py", line 276, in __bool__
    self._fetch_all()
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\models\sql\compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\cursors.py", line 247, in execute
    res = self._query(query)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\cursors.py", line 374, in _do_query
    db.query(q)
  File "C:\Users\Mololuwa\AppData\Local\Programs\Python\Python36-32\lib\site-packages\MySQLdb\connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'linuxjobber.courses_course' doesn't exist")
[2018-11-15 14:35:05] ERROR [django.server.log_message:124] "GET / HTTP/1.1" 500 243464
[2018-11-15 14:35:10] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2018-11-15 14:35:10] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 8845
[2018-11-15 14:37:24] INFO [django.server.log_message:124] "GET / HTTP/1.1" 200 21944
[2018-11-15 14:37:24] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/js/validation/jquery.validate.js HTTP/1.1" 200 3979
[2018-11-15 14:37:24] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/js/validation/jquery.validation.functions.js HTTP/1.1" 200 1163
[2018-11-15 14:37:24] INFO [django.server.log_message:124] "GET /static/home/css/style.css HTTP/1.1" 200 11247
[2018-11-15 14:37:24] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/css/style.css HTTP/1.1" 200 39923
[2018-11-15 14:37:24] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/css/bootstrap.min.css HTTP/1.1" 200 100261
[2018-11-15 14:37:24] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/css/newstyle2.css HTTP/1.1" 200 134612
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/css/newstylenew.css HTTP/1.1" 200 5356
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/css/newhomepage/css/main.css HTTP/1.1" 200 825
[2018-11-15 14:37:25] WARNING [django.request.get_response:93] Not Found: /images/icon5.png
[2018-11-15 14:37:25] WARNING [django.server.log_message:124] "GET /images/icon5.png HTTP/1.1" 404 8860
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/js/bootstrap.min.js HTTP/1.1" 200 29115
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/images/views.png HTTP/1.1" 200 5544
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/images/pupett.png HTTP/1.1" 200 8770
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/images/awssa.png HTTP/1.1" 200 13411
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/images/linuxx.png HTTP/1.1" 200 13722
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/images/tutor.png HTTP/1.1" 200 11460
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/images/q1.png HTTP/1.1" 200 1961
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/images/placement.png HTTP/1.1" 200 98335
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/images/training.png HTTP/1.1" 200 154154
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/images/dre.png HTTP/1.1" 200 22180
[2018-11-15 14:37:25] INFO [django.server.log_message:124] "GET /static/home/images/33.png HTTP/1.1" 200 62653
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/logo.png HTTP/1.1" 200 7177
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/hotels.png HTTP/1.1" 200 14387
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/ontario.png HTTP/1.1" 200 61470
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/faq/js/main.js HTTP/1.1" 200 4488
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/faq/js/jquery.mobile.custom.min.js HTTP/1.1" 200 9198
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/22.png HTTP/1.1" 200 62724
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/engine2.png HTTP/1.1" 200 4246
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/java.png HTTP/1.1" 200 14813
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/faq/js/jquery-2.1.1.js HTTP/1.1" 200 256541
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/hotelsafrica.png HTTP/1.1" 200 45205
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/q2.png HTTP/1.1" 200 1949
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/pupet.png HTTP/1.1" 200 5198
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/btns.png HTTP/1.1" 200 3954
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/44.png HTTP/1.1" 200 58580
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/kid.png HTTP/1.1" 200 13920
[2018-11-15 14:37:26] INFO [django.server.log_message:124] "GET /static/home/images/experience.png HTTP/1.1" 200 279224
[2018-11-15 14:37:27] INFO [django.server.log_message:124] "GET /static/home/css/newdesigner/fonts/fontsstylesheet.css HTTP/1.1" 200 3066
[2018-11-15 14:37:27] INFO [django.server.log_message:124] "GET /static/home/images/bannerr.png HTTP/1.1" 200 77329
[2018-11-15 14:37:28] WARNING [django.request.get_response:93] Not Found: /favicon.ico
[2018-11-15 14:37:28] WARNING [django.server.log_message:124] "GET /favicon.ico HTTP/1.1" 404 8845
