[2019-05-07 13:45:32] WARNING [django.request.log_response:228] Not Found: /home
[2019-05-07 13:45:33] WARNING [django.channels.server.log_action:149] HTTP GET /home 404 [2.00, 127.0.0.1:60627]
[2019-05-07 13:45:33] WARNING [django.request.log_response:228] Not Found: /favicon.ico
[2019-05-07 13:45:33] WARNING [django.channels.server.log_action:149] HTTP GET /favicon.ico 404 [0.09, 127.0.0.1:60627]
[2019-05-07 13:46:34] INFO [django.channels.server.log_action:147] HTTP GET /admin 302 [1.07, 127.0.0.1:60717]
[2019-05-07 13:46:35] INFO [django.channels.server.log_action:141] HTTP GET /admin/login/?next=/admin 200 [0.66, 127.0.0.1:60717]
[2019-05-07 13:46:35] INFO [django.channels.server.log_action:141] HTTP GET /static/admin/css/responsive.css 200 [0.25, 127.0.0.1:60720]
[2019-05-07 13:46:35] INFO [django.channels.server.log_action:141] HTTP GET /static/admin/css/login.css 200 [0.30, 127.0.0.1:60715]
[2019-05-07 13:46:35] INFO [django.channels.server.log_action:141] HTTP GET /static/admin/css/base.css 200 [0.33, 127.0.0.1:60717]
[2019-05-07 13:46:35] INFO [django.channels.server.log_action:141] HTTP GET /static/admin/css/fonts.css 200 [0.09, 127.0.0.1:60717]
[2019-05-07 13:46:37] INFO [django.channels.server.log_action:141] HTTP GET /static/admin/fonts/Roboto-Light-webfont.woff 200 [0.44, 127.0.0.1:60726]
[2019-05-07 13:46:37] INFO [django.channels.server.log_action:141] HTTP GET /static/admin/fonts/Roboto-Regular-webfont.woff 200 [0.46, 127.0.0.1:60727]
[2019-05-07 13:46:45] INFO [django.channels.server.log_action:141] HTTP POST /admin/login/?next=/admin 200 [0.75, 127.0.0.1:60741]
[2019-05-07 13:46:45] INFO [django.channels.server.log_action:141] HTTP GET /static/admin/fonts/Roboto-Bold-webfont.woff 200 [0.07, 127.0.0.1:60741]
[2019-05-07 13:46:54] INFO [django.channels.server.log_action:147] HTTP POST /admin/login/?next=/admin 302 [1.10, 127.0.0.1:60762]
[2019-05-07 13:46:55] INFO [django.channels.server.log_action:141] HTTP GET /admin 200 [0.60, 127.0.0.1:60762]
[2019-05-07 13:46:55] INFO [django.channels.server.log_action:141] HTTP GET /static/admin/css/dashboard.css 200 [0.06, 127.0.0.1:60762]
[2019-05-07 13:46:55] INFO [django.channels.server.log_action:141] HTTP GET /static/admin/img/icon-addlink.svg 200 [0.08, 127.0.0.1:60762]
[2019-05-07 13:46:55] INFO [django.channels.server.log_action:141] HTTP GET /static/admin/img/icon-changelink.svg 200 [0.09, 127.0.0.1:60761]
[2019-05-07 13:48:10] WARNING [django.request.log_response:228] Not Found: /linuxjobber/home
[2019-05-07 13:48:10] WARNING [django.channels.server.log_action:149] HTTP GET /linuxjobber/home 404 [0.16, 127.0.0.1:60877]
[2019-05-07 13:48:36] WARNING [django.request.log_response:228] Not Found: /index/home
[2019-05-07 13:48:36] WARNING [django.channels.server.log_action:149] HTTP GET /index/home 404 [0.17, 127.0.0.1:60911]
[2019-05-07 13:50:55] WARNING [django.request.log_response:228] Not Found: /index
[2019-05-07 13:50:55] WARNING [django.channels.server.log_action:149] HTTP GET /index 404 [0.19, 127.0.0.1:61062]
[2019-05-07 13:51:03] ERROR [django.request.log_response:228] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\josh\Desktop\linuxjobber2\Django\Linuxjobber\home\views.py", line 54, in index
    return render (request, 'home/index2.html')
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contact_us' not found. 'contact_us' is not a valid view function or pattern name.
[2019-05-07 13:51:03] ERROR [django.channels.server.log_action:154] HTTP GET / 500 [1.09, 127.0.0.1:61077]
[2019-05-07 13:57:18] WARNING [django.request.log_response:228] Not Found: /index
[2019-05-07 13:57:18] WARNING [django.channels.server.log_action:149] HTTP GET /index 404 [0.30, 127.0.0.1:61748]
[2019-05-07 13:57:25] INFO [django.channels.server.log_action:141] HTTP GET / 200 [0.49, 127.0.0.1:61758]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newdesigner/js/validation/jquery.validation.functions.js 200 [0.67, 127.0.0.1:61758]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newdesigner/js/validation/jquery.validate.js 200 [0.52, 127.0.0.1:61757]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newdesigner/css/bootstrap.min.css 200 [0.48, 127.0.0.1:61764]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/css/newstyle2.css 200 [0.45, 127.0.0.1:61761]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/style.css 200 [0.55, 127.0.0.1:61763]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newdesigner/css/style.css 200 [0.48, 127.0.0.1:61762]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/css/main.css 200 [0.25, 127.0.0.1:61758]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/css/newstylenew.css 200 [0.28, 127.0.0.1:61757]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newdesigner/fonts/fontsstylesheet.css 200 [0.17, 127.0.0.1:61764]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 200 [0.23, 127.0.0.1:61762]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/Projects/custom/css/projects.css 200 [0.24, 127.0.0.1:61763]
[2019-05-07 13:57:26] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 200 [0.20, 127.0.0.1:61761]
[2019-05-07 13:57:27] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-05-07 13:57:27] WARNING [django.channels.server.log_action:149] HTTP GET /images/icon5.png 404 [0.10, 127.0.0.1:61762]
[2019-05-07 13:57:27] INFO [django.channels.server.log_action:141] HTTP GET /static/home/images/logo.png 200 [0.15, 127.0.0.1:61763]
[2019-05-07 13:57:27] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newdesigner/js/bootstrap.min.js 200 [0.49, 127.0.0.1:61763]
[2019-05-07 13:57:27] INFO [django.channels.server.log_action:141] HTTP GET /static/home/images/logout1.png 200 [0.33, 127.0.0.1:61758]
[2019-05-07 13:57:27] INFO [django.channels.server.log_action:141] HTTP GET /static/home/images/icon1.png 200 [0.44, 127.0.0.1:61757]
[2019-05-07 13:57:27] INFO [django.channels.server.log_action:141] HTTP GET /static/faq/js/main.js 200 [0.45, 127.0.0.1:61761]
[2019-05-07 13:57:27] INFO [django.channels.server.log_action:141] HTTP GET /static/js/waterbubble.js 200 [0.31, 127.0.0.1:61764]
[2019-05-07 13:57:27] INFO [django.channels.server.log_action:141] HTTP GET /static/faq/js/jquery.mobile.custom.min.js 200 [0.47, 127.0.0.1:61762]
[2019-05-07 13:57:28] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/jobban2.png 200 [0.26, 127.0.0.1:61757]
[2019-05-07 13:57:28] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/homebanner.png 200 [0.27, 127.0.0.1:61758]
[2019-05-07 13:57:28] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/LaptopBook.png 200 [0.11, 127.0.0.1:61762]
[2019-05-07 13:57:28] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/jobphone.png 200 [0.47, 127.0.0.1:61762]
[2019-05-07 13:57:28] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/homelive.png 200 [0.43, 127.0.0.1:61757]
[2019-05-07 13:57:29] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/get3.png 200 [0.10, 127.0.0.1:61758]
[2019-05-07 13:57:29] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/get2.png 200 [0.13, 127.0.0.1:61764]
[2019-05-07 13:57:29] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/get1.png 200 [0.17, 127.0.0.1:61761]
[2019-05-07 13:57:29] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/testi.png 200 [0.09, 127.0.0.1:61757]
[2019-05-07 13:57:29] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/hq1.png 200 [0.09, 127.0.0.1:61762]
[2019-05-07 13:57:29] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/hq2.png 200 [0.11, 127.0.0.1:61764]
[2019-05-07 13:57:29] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/client3.png 200 [0.20, 127.0.0.1:61761]
[2019-05-07 13:57:29] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/client1.png 200 [0.16, 127.0.0.1:61757]
[2019-05-07 13:57:29] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/imgs/client2.png 200 [0.24, 127.0.0.1:61758]
[2019-05-07 13:57:30] INFO [django.channels.server.log_action:141] HTTP POST /ulocation 200 [0.49, 127.0.0.1:61762]
[2019-05-07 13:57:34] INFO [django.channels.server.log_action:141] HTTP GET /static/favicon.ico 200 [0.10, 127.0.0.1:61785]
[2019-05-07 13:57:41] INFO [django.channels.server.log_action:141] HTTP GET /aws/full_training 200 [0.32, 127.0.0.1:61796]
[2019-05-07 13:57:42] WARNING [django.request.log_response:228] Not Found: /aws/images/icon5.png
[2019-05-07 13:57:42] WARNING [django.channels.server.log_action:149] HTTP GET /aws/images/icon5.png 404 [0.24, 127.0.0.1:61796]
[2019-05-07 13:57:42] INFO [django.channels.server.log_action:141] HTTP GET /static/home/css/newhomepage/img/trialimg.jpg 200 [0.14, 127.0.0.1:61813]
[2019-05-07 13:57:42] INFO [django.channels.server.log_action:141] HTTP GET /static/home/images/selfs.png 200 [0.28, 127.0.0.1:61812]
[2019-05-07 13:57:50] INFO [django.channels.server.log_action:141] HTTP GET /devops/class/ 200 [0.20, 127.0.0.1:61845]
[2019-05-07 13:57:50] WARNING [django.request.log_response:228] Not Found: /devops/class/images/icon5.png
[2019-05-07 13:57:51] WARNING [django.channels.server.log_action:149] HTTP GET /devops/class/images/icon5.png 404 [0.10, 127.0.0.1:61845]
[2019-05-07 13:57:57] INFO [django.channels.server.log_action:141] HTTP GET /linux/full_training 200 [0.63, 127.0.0.1:61866]
[2019-05-07 13:57:58] WARNING [django.request.log_response:228] Not Found: /linux/images/icon5.png
[2019-05-07 13:57:58] WARNING [django.channels.server.log_action:149] HTTP GET /linux/images/icon5.png 404 [0.32, 127.0.0.1:61866]
[2019-05-07 13:59:13] INFO [django.channels.server.log_action:141] HTTP GET / 200 [0.23, 127.0.0.1:61971]
[2019-05-07 13:59:14] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-05-07 13:59:14] WARNING [django.channels.server.log_action:149] HTTP GET /images/icon5.png 404 [0.39, 127.0.0.1:61971]
[2019-05-07 13:59:15] INFO [django.channels.server.log_action:141] HTTP POST /ulocation 200 [0.04, 127.0.0.1:61971]
[2019-05-07 14:09:32] INFO [django.channels.server.log_action:141] HTTP GET / 200 [1.73, 127.0.0.1:62920]
[2019-05-07 14:09:34] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-05-07 14:09:34] WARNING [django.channels.server.log_action:149] HTTP GET /images/icon5.png 404 [0.37, 127.0.0.1:62920]
[2019-05-07 14:09:38] INFO [django.channels.server.log_action:141] HTTP POST /ulocation 200 [0.03, 127.0.0.1:62942]
[2019-05-07 14:09:44] INFO [django.channels.server.log_action:141] HTTP GET /static/favicon.ico 200 [0.08, 127.0.0.1:62961]
[2019-05-07 14:10:36] INFO [django.channels.server.log_action:141] HTTP GET /companys/contact 200 [0.20, 127.0.0.1:63029]
[2019-05-07 14:10:36] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 14:10:36] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.11, 127.0.0.1:63029]
[2019-05-07 14:11:16] ERROR [django.request.log_response:228] Internal Server Error: /companys/contact
Traceback (most recent call last):
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\josh\Desktop\linuxjobber2\Django\Linuxjobber\home\views.py", line 1093, in contact_us
    from_email = request.POST.get['from_email','']
TypeError: 'method' object is not subscriptable
[2019-05-07 14:11:16] ERROR [django.channels.server.log_action:154] HTTP POST /companys/contact 500 [0.44, 127.0.0.1:63100]
[2019-05-07 14:26:01] WARNING [django.request.log_response:228] Not Found: /companys
[2019-05-07 14:26:01] WARNING [django.channels.server.log_action:149] HTTP GET /companys 404 [1.45, 127.0.0.1:64616]
[2019-05-07 14:26:07] INFO [django.channels.server.log_action:141] HTTP GET / 200 [1.09, 127.0.0.1:64633]
[2019-05-07 14:26:08] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-05-07 14:26:08] WARNING [django.channels.server.log_action:149] HTTP GET /images/icon5.png 404 [0.10, 127.0.0.1:64633]
[2019-05-07 14:26:12] INFO [django.channels.server.log_action:141] HTTP POST /ulocation 200 [0.15, 127.0.0.1:64652]
[2019-05-07 14:26:29] INFO [django.channels.server.log_action:141] HTTP GET /companys/contact 200 [0.14, 127.0.0.1:64680]
[2019-05-07 14:26:30] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 14:26:30] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.18, 127.0.0.1:64680]
[2019-05-07 14:26:58] ERROR [django.request.log_response:228] Internal Server Error: /companys/contact
Traceback (most recent call last):
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\josh\Desktop\linuxjobber2\Django\Linuxjobber\home\views.py", line 1093, in contact_us
    from_email = request.POST.get['email','']
TypeError: 'method' object is not subscriptable
[2019-05-07 14:26:58] ERROR [django.channels.server.log_action:154] HTTP POST /companys/contact 500 [0.29, 127.0.0.1:64725]
[2019-05-07 14:27:45] INFO [django.channels.server.log_action:141] HTTP GET /companys/contact 200 [0.16, 127.0.0.1:64792]
[2019-05-07 14:30:39] INFO [django.channels.server.log_action:141] HTTP GET /companys/contact 200 [1.06, 127.0.0.1:65195]
[2019-05-07 14:30:39] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 14:30:39] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.23, 127.0.0.1:65200]
[2019-05-07 14:30:43] INFO [django.channels.server.log_action:141] HTTP GET /static/favicon.ico 200 [0.14, 127.0.0.1:65200]
[2019-05-07 14:32:16] ERROR [django.request.log_response:228] Internal Server Error: /companys/contact
Traceback (most recent call last):
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\josh\Desktop\linuxjobber2\Django\Linuxjobber\home\views.py", line 1094, in contact_us
    subject = request.POST.get['subject', '']
TypeError: 'method' object is not subscriptable
[2019-05-07 14:32:16] ERROR [django.channels.server.log_action:154] HTTP POST /companys/contact 500 [0.41, 127.0.0.1:65366]
[2019-05-07 14:33:43] INFO [django.channels.server.log_action:141] HTTP GET / 200 [0.92, 127.0.0.1:65490]
[2019-05-07 14:33:44] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-05-07 14:33:44] WARNING [django.channels.server.log_action:149] HTTP GET /images/icon5.png 404 [0.22, 127.0.0.1:65490]
[2019-05-07 14:33:46] INFO [django.channels.server.log_action:141] HTTP POST /ulocation 200 [0.04, 127.0.0.1:65502]
[2019-05-07 14:35:09] INFO [django.channels.server.log_action:141] HTTP GET /companys/contact 200 [1.26, 127.0.0.1:49266]
[2019-05-07 14:35:09] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 14:35:10] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.39, 127.0.0.1:49272]
[2019-05-07 14:35:30] ERROR [django.request.log_response:228] Internal Server Error: /companys/contact
Traceback (most recent call last):
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: ('subject', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\josh\Desktop\linuxjobber2\Django\Linuxjobber\home\views.py", line 1094, in contact_us
    subject = request.POST['subject', '']
  File "C:\Users\josh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django-2.1.5-py3.6.egg\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: ('subject', '')
[2019-05-07 14:35:30] ERROR [django.channels.server.log_action:154] HTTP POST /companys/contact 500 [0.63, 127.0.0.1:49312]
[2019-05-07 14:36:13] INFO [django.channels.server.log_action:141] HTTP GET /companys/contact 200 [0.98, 127.0.0.1:49396]
[2019-05-07 14:36:14] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 14:36:14] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.14, 127.0.0.1:49396]
[2019-05-07 14:37:08] INFO [django.channels.server.log_action:141] HTTP POST /companys/contact 200 [0.51, 127.0.0.1:49538]
[2019-05-07 14:37:08] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 14:37:08] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.20, 127.0.0.1:49538]
[2019-05-07 14:39:41] INFO [django.channels.server.log_action:141] HTTP POST /companys/contact 200 [0.19, 127.0.0.1:49717]
[2019-05-07 14:39:41] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 14:39:41] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.17, 127.0.0.1:49717]
[2019-05-07 15:02:13] INFO [django.channels.server.log_action:141] HTTP POST /companys/contact 200 [1.89, 127.0.0.1:51696]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/js/validation/jquery.validation.functions.js 304 [0.29, 127.0.0.1:51696]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/js/validation/jquery.validate.js 304 [0.28, 127.0.0.1:51695]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/style.css 304 [0.25, 127.0.0.1:51702]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/css/newstyle2.css 304 [0.27, 127.0.0.1:51700]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/css/style.css 304 [0.30, 127.0.0.1:51701]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/css/bootstrap.min.css 304 [0.35, 127.0.0.1:51703]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/css/main.css 304 [0.07, 127.0.0.1:51696]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/Projects/custom/css/projects.css 304 [0.09, 127.0.0.1:51695]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/css/newstylenew.css 304 [0.10, 127.0.0.1:51702]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 304 [0.13, 127.0.0.1:51701]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 304 [0.15, 127.0.0.1:51700]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/fonts/fontsstylesheet.css 304 [0.12, 127.0.0.1:51696]
[2019-05-07 15:02:14] INFO [django.channels.server.log_action:145] HTTP GET /static/home/images/logo.png 304 [0.05, 127.0.0.1:51696]
[2019-05-07 15:02:14] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 15:02:14] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.11, 127.0.0.1:51700]
[2019-05-07 15:02:15] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/js/bootstrap.min.js 304 [0.07, 127.0.0.1:51700]
[2019-05-07 15:02:15] INFO [django.channels.server.log_action:145] HTTP GET /static/js/waterbubble.js 304 [0.06, 127.0.0.1:51702]
[2019-05-07 15:02:15] INFO [django.channels.server.log_action:145] HTTP GET /static/faq/js/jquery.mobile.custom.min.js 304 [0.13, 127.0.0.1:51696]
[2019-05-07 15:02:15] INFO [django.channels.server.log_action:145] HTTP GET /static/faq/js/main.js 304 [0.14, 127.0.0.1:51701]
[2019-05-07 15:02:15] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/jobban2.png 304 [0.15, 127.0.0.1:51695]
[2019-05-07 15:02:21] INFO [django.channels.server.log_action:141] HTTP GET /static/favicon.ico 200 [0.07, 127.0.0.1:51726]
[2019-05-07 15:06:36] INFO [django.channels.server.log_action:141] HTTP GET / 200 [0.27, 127.0.0.1:52021]
[2019-05-07 15:06:37] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/LaptopBook.png 304 [0.11, 127.0.0.1:52024]
[2019-05-07 15:06:37] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-05-07 15:06:37] WARNING [django.channels.server.log_action:149] HTTP GET /images/icon5.png 404 [0.26, 127.0.0.1:52025]
[2019-05-07 15:06:38] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/jobphone.png 304 [0.06, 127.0.0.1:52025]
[2019-05-07 15:06:38] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/get1.png 304 [0.27, 127.0.0.1:52028]
[2019-05-07 15:06:38] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/get3.png 304 [0.50, 127.0.0.1:52026]
[2019-05-07 15:06:38] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/homelive.png 304 [0.82, 127.0.0.1:52024]
[2019-05-07 15:06:39] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/testi.png 304 [1.07, 127.0.0.1:52029]
[2019-05-07 15:06:39] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/get2.png 304 [1.31, 127.0.0.1:52027]
[2019-05-07 15:06:39] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/homebanner.png 304 [0.89, 127.0.0.1:52025]
[2019-05-07 15:06:39] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/hq1.png 304 [0.06, 127.0.0.1:52025]
[2019-05-07 15:06:39] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/hq2.png 304 [0.08, 127.0.0.1:52024]
[2019-05-07 15:06:39] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/client2.png 304 [0.12, 127.0.0.1:52029]
[2019-05-07 15:06:40] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/client1.png 304 [0.16, 127.0.0.1:52027]
[2019-05-07 15:06:40] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/client3.png 304 [0.17, 127.0.0.1:52025]
[2019-05-07 15:06:40] INFO [django.channels.server.log_action:141] HTTP POST /ulocation 200 [0.01, 127.0.0.1:52025]
[2019-05-07 15:07:34] INFO [django.channels.server.log_action:141] HTTP GET /companys/contact 200 [0.29, 127.0.0.1:52113]
[2019-05-07 15:07:35] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 15:07:35] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.21, 127.0.0.1:52113]
[2019-05-07 15:07:44] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 15:07:44] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.17, 127.0.0.1:52133]
[2019-05-07 15:09:07] INFO [django.channels.server.log_action:141] HTTP POST /companys/contact 200 [0.13, 127.0.0.1:52280]
[2019-05-07 15:09:07] WARNING [django.request.log_response:228] Not Found: /companys/images/icon5.png
[2019-05-07 15:09:07] WARNING [django.channels.server.log_action:149] HTTP GET /companys/images/icon5.png 404 [0.52, 127.0.0.1:52282]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:141] HTTP GET / 200 [4.84, 127.0.0.1:61099]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/style.css 304 [0.06, 127.0.0.1:61103]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/css/bootstrap.min.css 304 [0.11, 127.0.0.1:61101]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/css/style.css 304 [0.09, 127.0.0.1:61102]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/css/main.css 304 [0.13, 127.0.0.1:61105]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/css/newstyle2.css 304 [0.14, 127.0.0.1:61104]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/css/newstylenew.css 304 [0.17, 127.0.0.1:61106]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/Projects/custom/css/projects.css 304 [0.15, 127.0.0.1:61103]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/js/validation/jquery.validation.functions.js 304 [0.07, 127.0.0.1:61105]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/js/validation/jquery.validate.js 304 [0.13, 127.0.0.1:61102]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.css 304 [0.13, 127.0.0.1:61101]
[2019-05-08 08:09:53] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/jquery-ui-1.12.1.custom/jquery-ui.min.js 304 [0.10, 127.0.0.1:61104]
[2019-05-08 08:09:54] INFO [django.channels.server.log_action:145] HTTP GET /static/home/images/logo.png 304 [0.04, 127.0.0.1:61104]
[2019-05-08 08:09:54] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-05-08 08:09:54] WARNING [django.channels.server.log_action:149] HTTP GET /images/icon5.png 404 [0.19, 127.0.0.1:61101]
[2019-05-08 08:09:54] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/js/bootstrap.min.js 304 [0.11, 127.0.0.1:61105]
[2019-05-08 08:09:54] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newdesigner/fonts/fontsstylesheet.css 304 [0.17, 127.0.0.1:61104]
[2019-05-08 08:09:54] INFO [django.channels.server.log_action:145] HTTP GET /static/faq/js/jquery.mobile.custom.min.js 304 [0.06, 127.0.0.1:61104]
[2019-05-08 08:09:54] INFO [django.channels.server.log_action:145] HTTP GET /static/faq/js/main.js 304 [0.02, 127.0.0.1:61104]
[2019-05-08 08:09:54] INFO [django.channels.server.log_action:145] HTTP GET /static/js/waterbubble.js 304 [0.19, 127.0.0.1:61104]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/get3.png 304 [0.27, 127.0.0.1:61103]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/get2.png 304 [0.28, 127.0.0.1:61106]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/LaptopBook.png 304 [0.32, 127.0.0.1:61101]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/homelive.png 304 [0.32, 127.0.0.1:61102]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/jobphone.png 304 [0.35, 127.0.0.1:61105]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/get1.png 304 [0.01, 127.0.0.1:61105]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/testi.png 304 [0.02, 127.0.0.1:61105]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/hq1.png 304 [0.02, 127.0.0.1:61102]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/hq2.png 304 [0.02, 127.0.0.1:61101]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/client3.png 304 [0.04, 127.0.0.1:61106]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/client2.png 304 [0.06, 127.0.0.1:61103]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/client1.png 304 [0.06, 127.0.0.1:61105]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/jobban2.png 304 [0.02, 127.0.0.1:61105]
[2019-05-08 08:09:55] INFO [django.channels.server.log_action:145] HTTP GET /static/home/css/newhomepage/imgs/homebanner.png 304 [0.08, 127.0.0.1:61103]
[2019-05-08 08:10:03] INFO [django.channels.server.log_action:141] HTTP GET /companys/contact 200 [0.02, 127.0.0.1:61112]
[2019-05-08 08:10:04] WARNING [django.request.log_response:228] Not Found: /favicon.ico
[2019-05-08 08:10:04] WARNING [django.channels.server.log_action:149] HTTP GET /favicon.ico 404 [0.06, 127.0.0.1:61112]
[2019-05-08 08:10:11] WARNING [django.request.log_response:228] Not Found: /images/icon5.png
[2019-05-08 08:10:11] WARNING [django.channels.server.log_action:149] HTTP GET /images/icon5.png 404 [0.08, 127.0.0.1:61118]
[2019-05-08 08:10:14] INFO [django.channels.server.log_action:141] HTTP GET /companys/contact 200 [0.02, 127.0.0.1:61122]
